In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("iris.csv",header=None)

In [3]:
data

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
data[4].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: 4, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
k=LabelEncoder()
data[4]=k.fit_transform(data[4])


In [6]:
data

0    1    2    3  4
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]

In [7]:
data.shape

(150, 5)

In [8]:
data[4].value_counts()  #this is the for the counting the unique values in the data..

0    50
1    50
2    50
Name: 4, dtype: int64

In [9]:
data.columns=[0,1,2,3,"Target"]  #this is how we can chnage the columns name in the pandas ...

In [10]:
data

0    1    2    3  Target
0    5.1  3.5  1.4  0.2       0
1    4.9  3.0  1.4  0.2       0
2    4.7  3.2  1.3  0.2       0
3    4.6  3.1  1.5  0.2       0
4    5.0  3.6  1.4  0.2       0
..   ...  ...  ...  ...     ...
145  6.7  3.0  5.2  2.3       2
146  6.3  2.5  5.0  1.9       2
147  6.5  3.0  5.2  2.0       2
148  6.2  3.4  5.4  2.3       2
149  5.9  3.0  5.1  1.8       2

[150 rows x 5 columns]

In [11]:
data0=data.query("Target==0")  #this is also for the specify any condtion and the find out the data

In [12]:
data_0=data[(data.Target==0)]   #this is also for the specify any condtion and the find out the data

In [13]:
data_0.head()

0    1    2    3  Target
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [14]:
data0.head()

0    1    2    3  Target
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [15]:
data1=data.query("Target==1")

In [16]:
data_1=data[(data.Target==1)]

In [17]:
data1.head()

0    1    2    3  Target
50  7.0  3.2  4.7  1.4       1
51  6.4  3.2  4.5  1.5       1
52  6.9  3.1  4.9  1.5       1
53  5.5  2.3  4.0  1.3       1
54  6.5  2.8  4.6  1.5       1

In [18]:
data2=data.query("Target==2")

In [19]:
data2.head()

0    1    2    3  Target
100  6.3  3.3  6.0  2.5       2
101  5.8  2.7  5.1  1.9       2
102  7.1  3.0  5.9  2.1       2
103  6.3  2.9  5.6  1.8       2
104  6.5  3.0  5.8  2.2       2

In [20]:
data_2=data[(data.Target==2)]

In [21]:
data_2.head()

0    1    2    3  Target
100  6.3  3.3  6.0  2.5       2
101  5.8  2.7  5.1  1.9       2
102  7.1  3.0  5.9  2.1       2
103  6.3  2.9  5.6  1.8       2
104  6.5  3.0  5.8  2.2       2

In [22]:
data1=data1.drop("Target",axis=1)

In [23]:
data1.head()

0    1    2    3
50  7.0  3.2  4.7  1.4
51  6.4  3.2  4.5  1.5
52  6.9  3.1  4.9  1.5
53  5.5  2.3  4.0  1.3
54  6.5  2.8  4.6  1.5

In [24]:
data0=data0.drop("Target",axis=1)

In [25]:
data2=data2.drop("Target",axis=1)

In [26]:
data0.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [27]:
data2.head()

0    1    2    3
100  6.3  3.3  6.0  2.5
101  5.8  2.7  5.1  1.9
102  7.1  3.0  5.9  2.1
103  6.3  2.9  5.6  1.8
104  6.5  3.0  5.8  2.2

In [28]:
feature_mean=data[0].mean()

In [29]:
feature_mean

5.843333333333334

In [30]:
data_mean=data.mean()

In [31]:
data_mean

0         5.843333
1         3.054000
2         3.758667
3         1.198667
Target    1.000000
dtype: float64

In [32]:
def probility(m,s,x):
    exp1=np.exp(-(x-m)**2/2*s**2)
    return 1/np.sqrt(2*3.14*s**2)*exp1

In [33]:
data0_mean=list(data0.mean())

In [34]:
data0_mean

[5.006, 3.418, 1.464, 0.244]

In [35]:
data0_std=list(data0.std())

In [36]:
data1_mean=list(data1.mean())

In [37]:
data1_std=list(data1.std())

In [38]:
data1_std

[0.5161711470638634,
 0.3137983233784114,
 0.46991097723995795,
 0.19775268000454405]

In [39]:
def cal(m,s,x):
    
    for i,j,k in zip(m,s,x):
        print(i,j,k)
        k=probility(i,j,k)
        print(k)
        


In [40]:
x=[6.3,3.3,6.0,2.5]

In [41]:
final=[]

In [42]:
final.append(cal(data0_mean,data0_std,x))

5.006 0.35248968721345136 6.3
1.0202272951501177
3.418 0.38102439795469095 3.3
1.0462330465969363
1.464 0.17351115943644546 6.0
1.687262142952116
0.244 0.1072095030816784 2.5
3.614798608486597


In [43]:
k2=cal(data1_mean,data1_std,x)

5.936 0.5161711470638634 6.3
0.7595578946718937
2.7700000000000005 0.3137983233784114 3.3
1.254189774276671
4.26 0.46991097723995795 6.0
0.6079000919336425
1.3259999999999998 0.19775268000454405 2.5
1.9642364891726465


In [44]:
data.head(1)

0    1    2    3  Target
0  5.1  3.5  1.4  0.2       0

In [45]:
y=pd.DataFrame(data.Target)
x=data.drop("Target",axis=1)

In [77]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 1/3, random_state = 0)

In [78]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)
print("training Score: ",model.score(x_train,y_train))
print("testing Score: ", model.score(x_test,y_test))


training Score:  0.98
testing Score:  0.98


c:\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [79]:
from sklearn.svm import SVC # "Support vector classifier"
model = SVC(kernel='linear', C=1E10)
model.fit(x_train, y_train)
print("training Score: ",model.score(x_train,y_train))
print("testing Score: ", model.score(x_test,y_test))

training Score:  1.0
testing Score:  0.98


c:\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [80]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()
model.fit(x_train,y_train)
# predicted_classes = model.predict(x)
print("training Score: ",model.score(x_train,y_train))
print("testing Score: ", model.score(x_test,y_test))

training Score:  0.98
testing Score:  0.98


c:\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [81]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [83]:
for train,test in kf.split([1,2,3,5,5,2,59,92,38]):   #devide the data set in the given split number where k is given split number.
    print(train,test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
from model.selection import 