In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Logisticcodedata.csv")

In [3]:
data.head()

age  sallary Location  sales
0   25       44    noida      0
1   25       47    noida      0
2   29       88    noida      0
3   31       86  locknow      1
4   22      100  locknow      0

In [4]:
data=data.drop("Location",axis=1)

In [5]:
data.head()

age  sallary  sales
0   25       44      0
1   25       47      0
2   29       88      0
3   31       86      1
4   22      100      0

In [6]:
x1=data.age
x2=data.sallary
target=data.sales

In [7]:
x1

0     25
1     25
2     29
3     31
4     22
5     21
6     34
7     27
8     32
9     33
10    31
11    20
12    29
13    23
14    32
15    21
16    28
17    29
18    24
Name: age, dtype: int64

In [8]:
x1=np.array(x1)
x2=np.array(x2)
target=np.array(target)

In [9]:
x1

array([25, 25, 29, 31, 22, 21, 34, 27, 32, 33, 31, 20, 29, 23, 32, 21, 28,
       29, 24], dtype=int64)

In [10]:
data.max()

age         34
sallary    113
sales        1
dtype: int64

In [11]:
x1=x1/34
x2=x2/113

In [12]:
x1,x2

(array([0.73529412, 0.73529412, 0.85294118, 0.91176471, 0.64705882,
        0.61764706, 1.        , 0.79411765, 0.94117647, 0.97058824,
        0.91176471, 0.58823529, 0.85294118, 0.67647059, 0.94117647,
        0.61764706, 0.82352941, 0.85294118, 0.70588235]),
 array([0.38938053, 0.4159292 , 0.77876106, 0.76106195, 0.88495575,
        0.28318584, 0.88495575, 0.80530973, 0.90265487, 0.88495575,
        0.92920354, 0.3539823 , 0.81415929, 0.77876106, 1.        ,
        0.96460177, 0.71681416, 0.6460177 , 0.92920354]))

In [13]:
import random

In [14]:
w0=random.random()
w1=random.random()
w2=random.random()

In [15]:
w0

0.5856777504697346

In [16]:
y=w0+w1*x1+w2*x2

In [17]:
y

array([1.22570688, 1.22930263, 1.37241119, 1.41699734, 1.22235259,
       1.11735724, 1.50425248, 1.32902362, 1.45966633, 1.48076082,
       1.43977043, 1.10345425, 1.37720552, 1.23146124, 1.47285075,
       1.20964818, 1.34052945, 1.35443243, 1.27532882])

In [18]:
yp=1/(1+np.exp(-y))

In [19]:
yp

array([0.77306629, 0.77369649, 0.79776944, 0.80486726, 0.7724773 ,
       0.75349818, 0.81820786, 0.79067908, 0.81148164, 0.81468747,
       0.8084191 , 0.75090677, 0.79854182, 0.77407422, 0.8134903 ,
       0.77023669, 0.792577  , 0.79485333, 0.78165359])

In [20]:
loss=-1*sum(target*np.log(yp)+((1-target)*np.log(1-yp)))

In [21]:
loss

18.275952451707276

In [22]:
w0=random.random()
w1=random.random()
w2=random.random()
k=0
lr=.01
while(k<1000):
    k=k+1
    y=w0+w1*x1+w2*x2
    yp=1/(1+np.exp(-y))
    loss=-1*sum(target*np.log(yp)+((1-target)*np.log(1-yp)))
    print(loss)
    w0=w0-lr*sum(yp-target)
    w1=w1-lr*sum((yp-target)*x1)
    w2=w2-lr*sum((yp-target)*x2)
    

17.742978836377876
16.925554151123404
16.225051069058118
15.631142536800565
15.132341155921887
14.716778974705027
14.37285380484087
14.089699515831065
13.857478490288631
13.667521148329312
13.512349424616028
13.385621945597299
13.282033189225622
13.197191075102783
13.127489728588026
13.069987782819862
13.022297851818232
12.982489589105178
12.949006725300919
12.920597320816507
12.896255891847877
12.875175854209115
12.856710729303273
12.84034267008689
12.825657029824034
12.812321875764495
12.800071523193914
12.788693322492554
12.778017068959127
12.767906521734162
12.758252615529155
12.748968029180546
12.739982840691273
12.731241051722385
12.722697807564925
12.714317173299538
12.706070354700673
12.697934274767055
12.68989043463332
12.6819240019138
12.674023080958301
12.666178128632918
12.658381486536463
12.650627006393785
12.642909750025913
12.635225749019845
12.62757181219636
12.619945371352575
12.612344357657978
12.604767102603322
12.597212258618528
12.589678735448842
12.582165649157574

9.478841601664968
9.476769258539958
9.474699161584498
9.472631306572111
9.470565689287742
9.468502305527723
9.466441151099726
9.46438222182274
9.462325513527029
9.46027102205408
9.458218743256593
9.456168672998416
9.454120807154528
9.452075141610992
9.450031672264927
9.447990395024457
9.445951305808691
9.443914400547678
9.441879675182372
9.439847125664599
9.437816747957015
9.43578853803308
9.433762491877008
9.431738605483746
9.42971687485894
9.427697296018877
9.42567986499048
9.423664577811245
9.42165143052924
9.419640419203036
9.417631539901688
9.415624788704703
9.413620161702005
9.411617654993899
9.409617264691025
9.407618986914349
9.40562281779511
9.403628753474793
9.401636790105101
9.399646923847904
9.397659150875217
9.395673467369186
9.393689869522015
9.391708353535964
9.389728915623305
9.387751552006296
9.38577625891713
9.383803032597928
9.381831869300692
9.379862765287275
9.377895716829343
9.375930720208359
9.373967771715542
9.372006867651821
9.370048004327844
9.368091178063887


In [23]:
print(w0,w1,w2)

-4.61966090614348 2.5691018556052336 3.0126809343987646
